config/routes.rb
SeatingChart::Application.routes.draw do
  root :to => "seats#ajax"
  
  resources :seats
  resources :users
  resource :session
  
  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  match '/sit' => "seats#sit", :as => "sit"
  

  match ':controller(/:action(/:id(.:format)))'
end

app/models/seat.rb
class Seat < ActiveRecord::Base
end

app/models/user.rb
require 'digest'
class User < ActiveRecord::Base
  attr_accessor :password
  
  validates :email, :uniqueness => true, 
                    :length => { :within => 5..50 }, 
                    :format => { :with => /^[^@][\w.-]+@[\w.-]+[.][a-z]{2,4}$/i }
  validates :password, :confirmation => true,
                       :length => { :within => 4..20 },
                       :presence => true,
                       :if => :password_required?

  has_one :profile
  has_many :articles, :order => 'published_at DESC, title ASC',
                      :dependent => :nullify
  has_many :replies, :through => :articles, :source => :comments

  before_save :encrypt_new_password

  def self.authenticate(email, password)
    user = find_by_email(email)
    return user if user && user.authenticated?(password)
  end

  def authenticated?(password)
    self.hashed_password == encrypt(password)
  end

  protected
    def encrypt_new_password
      return if password.blank?
      self.hashed_password = encrypt(password)
    end

    def password_required?
      hashed_password.blank? || password.present?
    end

    def encrypt(string)
      Digest::SHA1.hexdigest(string)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  protected
    # Returns the currently logged in user or nil if there isn't one
    def current_user
      return unless session[:user_id]
      @current_user ||= User.find_by_id(session[:user_id])
    end

    def current_user_name
      user = User.find(current_user)
      user.email
    end
    # Make current_user available in templates as a helper
    helper_method :current_user

    # Filter method to enforce a login requirement
    # Apply as a before_filter on any controller you want to protect
    def authenticate
      logged_in? ? true : access_denied
    end

    # Predicate method to test for a logged in user
    def logged_in?
      current_user.is_a? User
    end

    # Make logged_in? available in templates as a helper
    helper_method :logged_in?

    def access_denied
      redirect_to login_path, :notice => "Please log in to continue" and return false
    end

    def remove_user
      @stand_up = Seat.where(:who => current_user_name)
      
      @stand_up.each do |stand|
        stand.update_attributes(:who => "")
      end
    end
end

app/controllers/seats_controller.rb
class SeatsController < ApplicationController
  
  before_filter :authenticate, :except => [:index, :ajax, :show]
  
  # GET /seats
  # GET /seats.xml
  def index
    @seats = Seat.find(:all, :order => 'id')
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @seats }
    end
  end
  
  # GET /seats
  # GET /seats.xml
  def ajax
    @seats = Seat.find(:all, :order => 'id')
    
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @seats }
    end
  end
  
  def sit
    @seats = Seat.find(params[:id])
    
    if @seats.who == ""
      remove_user
      @seats.update_attributes(:who => current_user_name)
    end
    
    respond_to do |format|
      format.xml  { render :xml => @seats }
    end
  end
  
  # GET /seats/1
  # GET /seats/1.xml
  def show
    @seat = Seat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @seat }
    end
  end

  # GET /seats/new
  # GET /seats/new.xml
  def new
    @seat = Seat.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @seat }
    end
  end

  # GET /seats/1/edit
  def edit
    @seat = Seat.find(params[:id])
  end

  # POST /seats
  # POST /seats.xml
  def create
    @seat = Seat.new(params[:seat])

    respond_to do |format|
      if @seat.save
        format.html { redirect_to(@seat, :notice => 'Seat was successfully created.') }
        format.xml  { render :xml => @seat, :status => :created, :location => @seat }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @seat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /seats/1
  # PUT /seats/1.xml
  def update
    @seat = Seat.find(params[:id])

    respond_to do |format|
      if @seat.update_attributes(params[:seat])
        format.html { redirect_to(@seat, :notice => 'Seat was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @seat.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /seats/1
  # DELETE /seats/1.xml
  def destroy
    @seat = Seat.find(params[:id])
    @seat.destroy

    respond_to do |format|
      format.html { redirect_to(seats_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    if user = User.authenticate(params[:email], params[:password])
      session[:user_id] = user.id
      redirect_to "/", :notice => "Logged in successfully"
    else
      flash.now[:alert] = "Invalid login/password combination"
      render :action => 'new'
    end
  end
  
  def destroy
    remove_user
    reset_session
    redirect_to "/", :notice => "You successfully logged out"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate, :only => [:edit, :update]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      redirect_to seats_path, :notice => 'User successfully added.'
    else
      render :action => 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      redirect_to seats_path, :notice => 'Updated user information successfully.'
    else
      render :action => 'edit'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/seats_helper.rb
module SeatsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SeatingChart</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag 'jquery-1.4.4.min', 'rails', 'application' %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/seats/_form.html.erb
<%= form_for(@seat) do |f| %>
  <% if @seat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@seat.errors.count, "error") %> prohibited this seat from being saved:</h2>

      <ul>
      <% @seat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :who %><br />
    <%= f.text_field :who %>
  </div>
  <div class="field">
    <%= f.label :computer %><br />
    <%= f.text_field :computer %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/seats/ajax.html.erb
<h1>Listing seats</h1>

<table id="seating_area">
<% a = 0%>
<% @seats.each do |seat| %>
  <% if a == 8 %>
    <% a = 0%>
    <tr></tr>
  <%end%>
  <td><%= seat.who %></td>
  <td><%= link_to seat.computer, sit_path(:id => seat.id), :remote => true %></td>
  <%a = a+1%>
<% end %>
</table>
<br />
<%= link_to "New User", :controller => "users", :action => "new" %>
<br />
<%= link_to "Log in", :controller => "login" %>
<br />
<%= link_to "Log out", :controller => "logout" %>
<br />

<script src="/messages.js"></script>

app/views/seats/chart.html.erb
<h1>Listing seats</h1>

<table>
  <tr>
    <th>Who</th>
    <th>Computer</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
<% a = 0%>
<% @seats.each do |seat| %>
  <% if a == 8 %>
    <% a = 0%>
    <tr></tr>
  <%end%>
  <td><%= seat.who %></td>
  <td><%= seat.computer %></td>
  <%a = a+1%>
<% end %>
</table>

<br />

app/views/seats/edit.html.erb
<h1>Editing seat</h1>

<%= render 'form' %>

<%= link_to 'Show', @seat %> |
<%= link_to 'Back', seats_path %>

app/views/seats/index.html.erb
<h1>Listing seats</h1>

<table>
<% a = 0%>
<% @seats.each do |seat| %>
  <% if a == 8 %>
    <% a = 0%>
    <tr></tr>
  <%end%>
  <td><%= seat.who %></td>
  <td><%= link_to seat.computer, :controller => "seats", :action => "sit", :id => seat.id %></td>
  <%a = a+1%>
<% end %>
</table>
<br />
<%= link_to "New User", :controller => "users", :action => "new" %>
<br />
<%= link_to "Log in", :controller => "login" %>
<br />
<%= link_to "Log out", :controller => "logout" %>
<br />

app/views/seats/new.html.erb
<h1>New seat</h1>

<%= render 'form' %>

<%= link_to 'Back', seats_path %>

app/views/seats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Who:</b>
  <%= @seat.who %>
</p>

<p>
  <b>Computer:</b>
  <%= @seat.computer %>
</p>


<%= link_to 'Edit', edit_seat_path(@seat) %> |
<%= link_to 'Back', seats_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
  <div id="errorExplanation">
    <h2><%= pluralize(@user.errors.count, "error") %>prohibited this user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>